"""add risk appetite and goals to user

Revision ID: e84226b70864
Revises: 92830ff8a965
Create Date: 2025-07-09 09:35:08.865701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84226b70864'
down_revision = '92830ff8a965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_data')
    op.drop_table('ltp')
    op.drop_table('timestamps')
    op.drop_table('symbols')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_appetite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('goal_short_term', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('goal_medium_term', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('goal_long_term', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('goal_long_term')
        batch_op.drop_column('goal_medium_term')
        batch_op.drop_column('goal_short_term')
        batch_op.drop_column('risk_appetite')

    op.create_table('symbols',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('yahoo_symbol', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yahoo_symbol', name=op.f('_yahoo_symbol_uc'))
    )
    op.create_table('timestamps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('operation', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ltp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('ltp', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('finance_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name=op.f('_symbol_date_uc'))
    )
    # ### end Alembic commands ###
